/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hotel.page;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import com.hotel.listener.HouseTypeListener;

/**
 *
 * @author Administrator
 */
public class HouseTypePage extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 6965258553869103830L;
	/**
     * Creates new form HouseTypePage
     */
    public HouseTypePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        houseTypePanel = new javax.swing.JPanel();
        addOrSearchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        houseTypeTextField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        houseTypeTable = new javax.swing.JTable();
        btnPanel = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "房间类型信息", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("宋体", 1, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        addOrSearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("查询增加"));

        jLabel1.setText("房间类型");

        addBtn.setText("增加");

        searchBtn.setText("查询");

        jLabel2.setText("描述");

        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        jScrollPane2.setViewportView(descTextArea);

        javax.swing.GroupLayout addOrSearchPanelLayout = new javax.swing.GroupLayout(addOrSearchPanel);
        addOrSearchPanel.setLayout(addOrSearchPanelLayout);
        addOrSearchPanelLayout.setHorizontalGroup(
            addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addOrSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addOrSearchPanelLayout.createSequentialGroup()
                        .addComponent(houseTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn)
                    .addComponent(searchBtn))
                .addGap(166, 166, 166))
        );
        addOrSearchPanelLayout.setVerticalGroup(
            addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addOrSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addOrSearchPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addBtn))
                    .addGroup(addOrSearchPanelLayout.createSequentialGroup()
                        .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(houseTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addOrSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("房间类型信息"));

        jScrollPane1.setViewportView(houseTypeTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout houseTypePanelLayout = new javax.swing.GroupLayout(houseTypePanel);
        houseTypePanel.setLayout(houseTypePanelLayout);
        houseTypePanelLayout.setHorizontalGroup(
            houseTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addOrSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        houseTypePanelLayout.setVerticalGroup(
            houseTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(houseTypePanelLayout.createSequentialGroup()
                .addComponent(addOrSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(houseTypePanel, java.awt.BorderLayout.CENTER);

        editBtn.setText("更新");
        btnPanel.add(editBtn);

        deleteBtn.setText("删除");
        btnPanel.add(deleteBtn);

        add(btnPanel, java.awt.BorderLayout.PAGE_END);
        
        initDefaultData();
		initEventListener();
    }// </editor-fold>//GEN-END:initComponents

	private void initDefaultData() {
		editBtn.setVisible(false);

		dataModel = new javax.swing.table.DefaultTableModel(new Object[][] {},
				new String[] { "类型名称", "描述", "创建时间", "更新时间", "编号" }) {
			private static final long serialVersionUID = 5886189813677606405L;
			@SuppressWarnings("rawtypes")
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class };

			@SuppressWarnings({ "rawtypes", "unchecked" })
			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return false;
			}
		};
		houseTypeTable.setModel(dataModel);
		TableColumn headerColumn = houseTypeTable.getTableHeader()
				.getColumnModel().getColumn(4);
		headerColumn.setMinWidth(0);
		headerColumn.setMaxWidth(0);
		headerColumn.setPreferredWidth(0);
		TableColumn rowColumn = houseTypeTable.getColumnModel().getColumn(4);
		rowColumn.setMinWidth(0);
		rowColumn.setMaxWidth(0);
		rowColumn.setPreferredWidth(0);
		
	}

	private void initEventListener() {
		addBtn.setActionCommand(HouseTypeListener.ADD_BTN_COMMAND);
		addBtn.addActionListener(new HouseTypeListener(this));
		
		searchBtn.setActionCommand(HouseTypeListener.SEARCH_BTN_COMMAND);
		searchBtn.addActionListener(new HouseTypeListener(this));
		
		deleteBtn.setActionCommand(HouseTypeListener.DELETE_BTN_COMMAND);
		deleteBtn.addActionListener(new HouseTypeListener(this));
	}
	
	public String getDescription(){
		return descTextArea.getText();
	}
	
	public String getHouseTypeName(){
		return houseTypeTextField.getText();
	}
	
	public DefaultTableModel getTableDataModel(){
		return dataModel;
	}
	
	public javax.swing.JTable getHouseTypeTable(){
		return houseTypeTable;
	}
	
	public void clearData() {
		int count = dataModel.getRowCount();
		for (int index = count - 1; index >= 0; index--) {
			dataModel.removeRow(index);
		}
		houseTypeTextField.setText("");
		descTextArea.setText("");
	}
	
	private DefaultTableModel dataModel;
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel addOrSearchPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel houseTypePanel;
    private javax.swing.JTable houseTypeTable;
    private javax.swing.JTextField houseTypeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
